i am unable to load my boston price prediction data set so instead of it i have predict it on another data set


In [ ]:
# 1. Create examples of zero vector, one vector, square matrix, diagonal matrix, identity matrix, and symmetricmatrix one by one, and represent vectors and matrices with NumPy.
import numpy as np

# Zero vector
zero_vector = np.zeros(5)
print("Zero vector:", zero_vector)

# One vector (all elements are 1)
one_vector = np.ones(3)
print("One vector:", one_vector)

# Square matrix
square_matrix = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])
print("Square matrix:")
print(square_matrix)

# Diagonal matrix
diagonal_matrix = np.diag([1, 2, 3])
print("Diagonal matrix:")
print(diagonal_matrix)

# Identity matrix
identity_matrix = np.identity(3)
print("Identity matrix:")
print(identity_matrix)

# Symmetric matrix
symmetric_matrix = np.array([[1, 2, 3],
                             [2, 4, 5],
                             [3, 5, 6]])
print("Symmetric matrix:")
print(symmetric_matrix)

Zero vector: [0. 0. 0. 0. 0.]
One vector: [1. 1. 1.]
Square matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]]
Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Symmetric matrix:
[[1 2 3]
 [2 4 5]
 [3 5 6]]


In [ ]:
#Q-2
import numpy as np

# Stock prices
p = np.array([1000000, 800000, 500000])

# Quantity of shares
n = np.array([3, 4, 5])

# Calculate the amount required to purchase stocks
amount = np.dot(p, n)

print("The total amount required to purchase the stocks is:", amount, "won")

The total amount required to purchase the stocks is: 8700000 won


In [ ]:
# Q-3
from sklearn.datasets import load_digits
X = load_digits().data

# Extract the first and tenth images
image1 = X[0]
image10 = X[9]

# Calculate the dot product
similarity = np.dot(image1, image10)

print("Similarity between the first and tenth image:", similarity)

Similarity between the first and tenth image: 2807.0


In [ ]:
X

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [ ]:
image1

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [ ]:
image10

array([ 0.,  0., 11., 12.,  0.,  0.,  0.,  0.,  0.,  2., 16., 16., 16.,
       13.,  0.,  0.,  0.,  3., 16., 12., 10., 14.,  0.,  0.,  0.,  1.,
       16.,  1., 12., 15.,  0.,  0.,  0.,  0., 13., 16.,  9., 15.,  2.,
        0.,  0.,  0.,  0.,  3.,  0.,  9., 11.,  0.,  0.,  0.,  0.,  0.,
        9., 15.,  4.,  0.,  0.,  0.,  9., 12., 13.,  3.,  0.,  0.])

HOUSE PRICE PREDICTION


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


In [5]:
import pandas as pd

# Load the dataset
file_path = 'sample_submission.csv'
df = pd.read_csv(file_path)

# Inspect the DataFrame
print(df.head())
print(df.info())

     Id      SalePrice
0  1461  169277.052498
1  1462  187758.393989
2  1463  183583.683570
3  1464  179317.477511
4  1465  150730.079977
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Id         1459 non-null   int64  
 1   SalePrice  1459 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 22.9 KB
None


In [6]:
# Identify categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_columns)

Categorical columns: Index([], dtype='object')


In [7]:
numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns

In [8]:
# Transform categorical columns using One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=categorical_columns)

# Verify the transformation
print(df_encoded.head())
print(df_encoded.info())

     Id      SalePrice
0  1461  169277.052498
1  1462  187758.393989
2  1463  183583.683570
3  1464  179317.477511
4  1465  150730.079977
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Id         1459 non-null   int64  
 1   SalePrice  1459 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 22.9 KB
None


In [10]:
import pandas as pd

# Load the dataset
file_path = 'sample_submission.csv'
df = pd.read_csv(file_path)

# Inspect the DataFrame
print("DataFrame Head:\n", df.head())
print("DataFrame Info:\n", df.info())

# Identify categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_columns)

# Strip any whitespace from column names (if any)
df.columns = df.columns.str.strip()

# Transform categorical columns using One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=categorical_columns)

# Verify the transformation
print("Transformed DataFrame Head:\n", df_encoded.head())
print("Transformed DataFrame Info:\n", df_encoded.info())

DataFrame Head:
      Id      SalePrice
0  1461  169277.052498
1  1462  187758.393989
2  1463  183583.683570
3  1464  179317.477511
4  1465  150730.079977
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Id         1459 non-null   int64  
 1   SalePrice  1459 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 22.9 KB
DataFrame Info:
 None
Categorical columns: Index([], dtype='object')
Transformed DataFrame Head:
      Id      SalePrice
0  1461  169277.052498
1  1462  187758.393989
2  1463  183583.683570
3  1464  179317.477511
4  1465  150730.079977
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Id         1459 non-null   int64  
 1   SalePrice  1459 non-null   float64
dtypes: float64(1), int64(

In [13]:
X = df_encoded.drop("SalePrice",axis =1)
y = df_encoded["SalePrice"]

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [15]:
from sklearn.svm import SVR
svr = SVR(kernel = "linear")
svr.fit(X_train, y_train)
y_pred = svr.predict(X_test)

In [16]:
y_pred

array([180788.40810477, 176638.55063171, 181475.19494834, 180950.73954051,
       177708.2731699 , 176330.53713822, 180871.6549949 , 180313.90083101,
       176834.18082352, 180667.70011409, 180005.88733753, 179523.05537476,
       180151.56939527, 176759.25862241, 181279.56475653, 178777.9957081 ,
       181146.36973233, 180255.62800793, 177837.3058496 , 178682.26178444,
       180472.06992226, 177354.47388684, 182128.68303587, 181225.45427797,
       179431.48379564, 181283.72710105, 179568.84116434, 176509.51795202,
       180426.2841327 , 181187.99317741, 178986.11293342, 179697.87384405,
       177916.39039522, 179127.63264664, 178411.70939151, 182087.05959084,
       177025.64867081, 181287.88944557, 177300.36340826, 180596.94025745,
       181387.78571369, 180476.23226678, 176555.30374158, 177208.79182912,
       177441.88312148, 180238.97862989, 179997.56264853, 176397.13465033,
       177766.54599299, 181912.24112155, 178586.52786078, 180613.58963548,
       180026.69906006, 1

In [17]:
submission = pd.DataFrame({"Id":range(len(y_pred)),
                         "SalePrice": y_pred})

In [18]:
submission

Id      SalePrice
0      0  180788.408105
1      1  176638.550632
2      2  181475.194948
3      3  180950.739541
4      4  177708.273170
..   ...            ...
287  287  177341.986853
288  288  182003.812701
289  289  176721.797522
290  290  180929.927818
291  291  181371.136336

[292 rows x 2 columns]